### ISSUE TITLE
Validating arguments via assert

### ISSUE THREAD

**Issue by dy** [compute-io/contributing#2]
Hello @compute-io team!

Just rediscovered how useful your org is, thank you for that!

One thing from contrib guidelines drew my attention. You suggest contributors validating arguments via `if`, but for that purpose there exists an alternate (prob better) solution - `assert` with [`unassertify`](https://www.npmjs.com/package/unassertify). That allows for better error messages, better debugging and  better performance in production, by removing asserts via `unassertify` transform. In @audiojs we opted for that, following @choojs and related packages.

How would you consider that practice?

**Comment by kgryte** [comment]
Not something we are interested in doing.

1. __Error messages__. Not sure how error messages are "better",  per se. The message would be the same.
2. __Debugging__. Not sure how debugging is "better" either. If anything, debugging is "better" by inlining assertions, as, e.g., throwing is localized to the interface which is directly responsible for validating inputs, not an external library. Hence, when an error is thrown, there is no uncertainty as to whether an error is "programmer" (e.g., an error in the assertion library which throws) or "operational" (e.g., invalid input from external consumers).
3. __Performance__. Most assertions (e.g., of the type checking variety) are unlikely to be performance bottlenecks and will be negligible compared to the rest of an implementation (note, however, this is not necessarily true for `object` properties, where, in JS, own property look-up is comparatively slow). Further, modern compilers are fairly decent at removing code paths which are not traversed. Hence, something like `unassertify` is more likely to provide a network boost (fewer bytes over the wire) than a runtime performance boost. Lastly, removing assertions is not something we encourage, as this means that remote debugging (including, e.g., in a browser console) cannot leverage interface assertions (e.g., if I drop into the browser console in my production web app and provide an invalid input argument, I may encounter silent errors which would be obvious had I left the assertions).

If you are adamant about removing assertions, nothing is stopping you from parsing the AST, finding conditionals which contain, e.g., a single `throw` statement, and removing those nodes from generated output.
